--- #YAML:1.0
name:               KiokuDB-Backend-Files
version:            0.06
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Directory::Transactional:  0.06
    File::Path:           2.07
    IO:                   1.2301
    KiokuDB:              0.24
    Moose:                0
    MooseX::Types::Path::Class:  0
    Test::TempDir:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
